name: New content idea
description: Easily create a new content article.
title: "[NEW CONTENT IDEA]"
labels: ["doc-idea", "doc-enhancement", "sample-idea"]
assignees: 
  - digitaldiina
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to share your ideas!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for your suggestion.
      options:
      - label: I have searched the existing issues
        required: true
  - type: dropdown
    id: type
    attributes:
      label: What kind of idea is it?
      multiple: true
      options:
        - New page on SuperOfficeDocs
        - Add or revise existing page
        - Create sample
        - Other
  - type: dropdown
    id: audience
    attributes:
      label: Who is it for?
      multiple: true
      options:
        - User (Learn)
        - Administrator
        - Consultant
        - Developer
        - Other
  - type: dropdown
    id: topic
    attributes:
      label: Which area (SuperOffice entity) is this related to?
      multiple: true
      options:
        - Company, contact
        - Diary
        - Document
        - Email
        - Project
        - Request
        - Sale
        - Other
  - type: textarea
    attributes:
      label: Description
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      placeholder: Tell us about your idea!
    validations:
      required: false
  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
