### YamlMime:ManagedReference
items:
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest
  commentId: T:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest
  id: Audience_DeleteConfigParameterRequest
  parent: SuperOffice.WebApi.Data
  children:
  - SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.#ctor
  - SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName
  - SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName
  langs:
  - csharp
  - vb
  name: Audience_DeleteConfigParameterRequest
  nameWithType: Audience_DeleteConfigParameterRequest
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest
  type: Class
  assemblies:
  - SuperOffice.WebApi
  namespace: SuperOffice.WebApi.Data
  example: []
  syntax:
    content: public class Audience_DeleteConfigParameterRequest
    content.vb: Public Class Audience_DeleteConfigParameterRequest
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.#ctor
  commentId: M:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.#ctor
  id: '#ctor'
  parent: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest
  langs:
  - csharp
  - vb
  name: Audience_DeleteConfigParameterRequest()
  nameWithType: Audience_DeleteConfigParameterRequest.Audience_DeleteConfigParameterRequest()
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.Audience_DeleteConfigParameterRequest()
  type: Constructor
  assemblies:
  - SuperOffice.WebApi
  namespace: SuperOffice.WebApi.Data
  syntax:
    content: public Audience_DeleteConfigParameterRequest()
    content.vb: Public Sub New()
  overload: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.#ctor*
  nameWithType.vb: Audience_DeleteConfigParameterRequest.New()
  fullName.vb: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.New()
  name.vb: New()
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName
  commentId: P:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName
  id: LayoutName
  parent: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest
  langs:
  - csharp
  - vb
  name: LayoutName
  nameWithType: Audience_DeleteConfigParameterRequest.LayoutName
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName
  type: Property
  assemblies:
  - SuperOffice.WebApi
  namespace: SuperOffice.WebApi.Data
  example: []
  syntax:
    content: public string LayoutName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LayoutName As String
  overload: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName*
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName
  commentId: P:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName
  id: ParameterName
  parent: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest
  langs:
  - csharp
  - vb
  name: ParameterName
  nameWithType: Audience_DeleteConfigParameterRequest.ParameterName
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName
  type: Property
  assemblies:
  - SuperOffice.WebApi
  namespace: SuperOffice.WebApi.Data
  example: []
  syntax:
    content: public string ParameterName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ParameterName As String
  overload: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName*
references:
- uid: SuperOffice.WebApi.Data
  commentId: N:SuperOffice.WebApi.Data
  isExternal: true
  href: SuperOffice.html
  name: SuperOffice.WebApi.Data
  nameWithType: SuperOffice.WebApi.Data
  fullName: SuperOffice.WebApi.Data
  spec.csharp:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.WebApi
    name: WebApi
    isExternal: true
    href: SuperOffice.WebApi.html
  - name: .
  - uid: SuperOffice.WebApi.Data
    name: Data
    isExternal: true
    href: SuperOffice.WebApi.Data.html
  spec.vb:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.WebApi
    name: WebApi
    isExternal: true
    href: SuperOffice.WebApi.html
  - name: .
  - uid: SuperOffice.WebApi.Data
    name: Data
    isExternal: true
    href: SuperOffice.WebApi.Data.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.#ctor*
  commentId: Overload:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.#ctor
  isExternal: true
  href: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.html#SuperOffice_WebApi_Data_Audience_DeleteConfigParameterRequest__ctor
  name: Audience_DeleteConfigParameterRequest
  nameWithType: Audience_DeleteConfigParameterRequest.Audience_DeleteConfigParameterRequest
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.Audience_DeleteConfigParameterRequest
  nameWithType.vb: Audience_DeleteConfigParameterRequest.New
  fullName.vb: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.New
  name.vb: New
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName*
  commentId: Overload:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName
  isExternal: true
  href: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.html#SuperOffice_WebApi_Data_Audience_DeleteConfigParameterRequest_LayoutName
  name: LayoutName
  nameWithType: Audience_DeleteConfigParameterRequest.LayoutName
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.LayoutName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName*
  commentId: Overload:SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName
  isExternal: true
  href: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.html#SuperOffice_WebApi_Data_Audience_DeleteConfigParameterRequest_ParameterName
  name: ParameterName
  nameWithType: Audience_DeleteConfigParameterRequest.ParameterName
  fullName: SuperOffice.WebApi.Data.Audience_DeleteConfigParameterRequest.ParameterName
