### YamlMime:ManagedReference
items:
- uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
  commentId: T:SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
  id: ISoEnvironmentInfoPlugin
  parent: SuperOffice.Diagnostics
  children:
  - SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo(System.Collections.Specialized.NameValueCollection)
  langs:
  - csharp
  - vb
  name: ISoEnvironmentInfoPlugin
  nameWithType: ISoEnvironmentInfoPlugin
  fullName: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
  type: Interface
  assemblies:
  - SoCore
  namespace: SuperOffice.Diagnostics
  summary: Interface should be implemented for plugins wanting to provide environment info while logging.
  example: []
  syntax:
    content: public interface ISoEnvironmentInfoPlugin
    content.vb: Public Interface ISoEnvironmentInfoPlugin
  extensionMethods:
  - SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.EnumUtil.MapEnums``2
  - SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
- uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo(System.Collections.Specialized.NameValueCollection)
  commentId: M:SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo(System.Collections.Specialized.NameValueCollection)
  id: UpdateEnvironmentInfo(System.Collections.Specialized.NameValueCollection)
  parent: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
  langs:
  - csharp
  - vb
  name: UpdateEnvironmentInfo(NameValueCollection)
  nameWithType: ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo(NameValueCollection)
  fullName: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo(System.Collections.Specialized.NameValueCollection)
  type: Method
  assemblies:
  - SoCore
  namespace: SuperOffice.Diagnostics
  summary: Method called to collect extra environment info
  example: []
  syntax:
    content: void UpdateEnvironmentInfo(NameValueCollection environmentInfo)
    parameters:
    - id: environmentInfo
      type: System.Collections.Specialized.NameValueCollection
      description: ''
    content.vb: Sub UpdateEnvironmentInfo(environmentInfo As NameValueCollection)
  overload: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo*
references:
- uid: SuperOffice.Diagnostics
  commentId: N:SuperOffice.Diagnostics
  isExternal: true
  href: SuperOffice.html
  name: SuperOffice.Diagnostics
  nameWithType: SuperOffice.Diagnostics
  fullName: SuperOffice.Diagnostics
  spec.csharp:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.Diagnostics
    name: Diagnostics
    isExternal: true
    href: SuperOffice.Diagnostics.html
  spec.vb:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.Diagnostics
    name: Diagnostics
    isExternal: true
    href: SuperOffice.Diagnostics.html
- uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.EnumUtil.MapEnums``2
  commentId: M:EnumUtil.MapEnums``2(``0)
  parent: EnumUtil
  definition: EnumUtil.MapEnums``2(``0)
  href: EnumUtil.html#EnumUtil_MapEnums__2___0_
  name: MapEnums<ISoEnvironmentInfoPlugin, To>(ISoEnvironmentInfoPlugin)
  nameWithType: EnumUtil.MapEnums<ISoEnvironmentInfoPlugin, To>(ISoEnvironmentInfoPlugin)
  fullName: EnumUtil.MapEnums<SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin, To>(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
  nameWithType.vb: EnumUtil.MapEnums(Of ISoEnvironmentInfoPlugin, To)(ISoEnvironmentInfoPlugin)
  fullName.vb: EnumUtil.MapEnums(Of SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin, To)(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
  name.vb: MapEnums(Of ISoEnvironmentInfoPlugin, To)(ISoEnvironmentInfoPlugin)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
    name: MapEnums
    isExternal: true
    href: EnumUtil.html#EnumUtil_MapEnums__2___0_
  - name: <
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: ','
  - name: " "
  - name: To
  - name: '>'
  - name: (
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
    name: MapEnums
    isExternal: true
    href: EnumUtil.html#EnumUtil_MapEnums__2___0_
  - name: (
  - name: Of
  - name: " "
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: ','
  - name: " "
  - name: To
  - name: )
  - name: (
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: )
- uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  parent: SuperOffice.ErpSync.ConnectorWS.Converters
  definition: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  href: SuperOffice.ErpSync.ConnectorWS.Converters.html#SuperOffice_ErpSync_ConnectorWS_Converters_MapEnums__2___0_
  name: MapEnums<ISoEnvironmentInfoPlugin, To>(ISoEnvironmentInfoPlugin)
  nameWithType: Converters.MapEnums<ISoEnvironmentInfoPlugin, To>(ISoEnvironmentInfoPlugin)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin, To>(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
  nameWithType.vb: Converters.MapEnums(Of ISoEnvironmentInfoPlugin, To)(ISoEnvironmentInfoPlugin)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin, To)(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
  name.vb: MapEnums(Of ISoEnvironmentInfoPlugin, To)(ISoEnvironmentInfoPlugin)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
    name: MapEnums
    isExternal: true
    href: SuperOffice.ErpSync.ConnectorWS.Converters.html#SuperOffice_ErpSync_ConnectorWS_Converters_MapEnums__2___0_
  - name: <
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: ','
  - name: " "
  - name: To
  - name: '>'
  - name: (
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin)
    name: MapEnums
    isExternal: true
    href: SuperOffice.ErpSync.ConnectorWS.Converters.html#SuperOffice_ErpSync_ConnectorWS_Converters_MapEnums__2___0_
  - name: (
  - name: Of
  - name: " "
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: ','
  - name: " "
  - name: To
  - name: )
  - name: (
  - uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin
    name: ISoEnvironmentInfoPlugin
    isExternal: true
    href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html
  - name: )
- uid: EnumUtil.MapEnums``2(``0)
  commentId: M:EnumUtil.MapEnums``2(``0)
  isExternal: true
  href: EnumUtil.html#EnumUtil_MapEnums__2___0_
  name: MapEnums<From, To>(From)
  nameWithType: EnumUtil.MapEnums<From, To>(From)
  fullName: EnumUtil.MapEnums<From, To>(From)
  nameWithType.vb: EnumUtil.MapEnums(Of From, To)(From)
  fullName.vb: EnumUtil.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums
    isExternal: true
    href: EnumUtil.html#EnumUtil_MapEnums__2___0_
  - name: <
  - name: From
  - name: ','
  - name: " "
  - name: To
  - name: '>'
  - name: (
  - name: From
  - name: )
  spec.vb:
  - uid: EnumUtil.MapEnums``2(``0)
    name: MapEnums
    isExternal: true
    href: EnumUtil.html#EnumUtil_MapEnums__2___0_
  - name: (
  - name: Of
  - name: " "
  - name: From
  - name: ','
  - name: " "
  - name: To
  - name: )
  - name: (
  - name: From
  - name: )
- uid: EnumUtil
  commentId: T:EnumUtil
  isExternal: true
  href: EnumUtil.html
  name: EnumUtil
  nameWithType: EnumUtil
  fullName: EnumUtil
- uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  commentId: M:SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
  isExternal: true
  href: SuperOffice.ErpSync.ConnectorWS.Converters.html#SuperOffice_ErpSync_ConnectorWS_Converters_MapEnums__2___0_
  name: MapEnums<From, To>(From)
  nameWithType: Converters.MapEnums<From, To>(From)
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums<From, To>(From)
  nameWithType.vb: Converters.MapEnums(Of From, To)(From)
  fullName.vb: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums(Of From, To)(From)
  name.vb: MapEnums(Of From, To)(From)
  spec.csharp:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums
    isExternal: true
    href: SuperOffice.ErpSync.ConnectorWS.Converters.html#SuperOffice_ErpSync_ConnectorWS_Converters_MapEnums__2___0_
  - name: <
  - name: From
  - name: ','
  - name: " "
  - name: To
  - name: '>'
  - name: (
  - name: From
  - name: )
  spec.vb:
  - uid: SuperOffice.ErpSync.ConnectorWS.Converters.MapEnums``2(``0)
    name: MapEnums
    isExternal: true
    href: SuperOffice.ErpSync.ConnectorWS.Converters.html#SuperOffice_ErpSync_ConnectorWS_Converters_MapEnums__2___0_
  - name: (
  - name: Of
  - name: " "
  - name: From
  - name: ','
  - name: " "
  - name: To
  - name: )
  - name: (
  - name: From
  - name: )
- uid: SuperOffice.ErpSync.ConnectorWS.Converters
  commentId: T:SuperOffice.ErpSync.ConnectorWS.Converters
  parent: SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  href: SuperOffice.ErpSync.ConnectorWS.Converters.html
  name: Converters
  nameWithType: Converters
  fullName: SuperOffice.ErpSync.ConnectorWS.Converters
- uid: SuperOffice.ErpSync.ConnectorWS
  commentId: N:SuperOffice.ErpSync.ConnectorWS
  isExternal: true
  href: SuperOffice.html
  name: SuperOffice.ErpSync.ConnectorWS
  nameWithType: SuperOffice.ErpSync.ConnectorWS
  fullName: SuperOffice.ErpSync.ConnectorWS
  spec.csharp:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.ErpSync
    name: ErpSync
    isExternal: true
    href: SuperOffice.ErpSync.html
  - name: .
  - uid: SuperOffice.ErpSync.ConnectorWS
    name: ConnectorWS
    isExternal: true
    href: SuperOffice.ErpSync.ConnectorWS.html
  spec.vb:
  - uid: SuperOffice
    name: SuperOffice
    isExternal: true
    href: SuperOffice.html
  - name: .
  - uid: SuperOffice.ErpSync
    name: ErpSync
    isExternal: true
    href: SuperOffice.ErpSync.html
  - name: .
  - uid: SuperOffice.ErpSync.ConnectorWS
    name: ConnectorWS
    isExternal: true
    href: SuperOffice.ErpSync.ConnectorWS.html
- uid: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo*
  commentId: Overload:SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo
  isExternal: true
  href: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.html#SuperOffice_Diagnostics_ISoEnvironmentInfoPlugin_UpdateEnvironmentInfo_System_Collections_Specialized_NameValueCollection_
  name: UpdateEnvironmentInfo
  nameWithType: ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo
  fullName: SuperOffice.Diagnostics.ISoEnvironmentInfoPlugin.UpdateEnvironmentInfo
- uid: System.Collections.Specialized.NameValueCollection
  commentId: T:System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.collections.specialized.namevaluecollection
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Collections.Specialized
  commentId: N:System.Collections.Specialized
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Collections.Specialized
  nameWithType: System.Collections.Specialized
  fullName: System.Collections.Specialized
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Specialized
    name: Specialized
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.specialized
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Collections
    name: Collections
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections
  - name: .
  - uid: System.Collections.Specialized
    name: Specialized
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.collections.specialized
